steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/funnyscar/linda-account-service', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/funnyscar/linda-account-service']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'linda-account-service',
           '--image', 'gcr.io/funnyscar/linda-account-service',
           '--platform', 'managed',
           '--region', 'us-central1',
           '--allow-unauthenticated']
images:
  - 'gcr.io/funnyscar/account-service'

serviceAccount: 'firebase-adminsdk-r5s26@funnyscar.iam.gserviceaccount.com'
options:
  logging: CLOUD_LOGGING_ONLY
